<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class TeachersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('teachers')->insert([
            'prefix' => 'ผู้ช่วยศาสตราจารย์ ดร.',
            'name' => 'ศักดิ์ชาญ',
            'surname' => 'เหลืองมณีโรจน์',
            'academic_position' => 'ผู้ช่วยศาสตราจารย์',
            'educational_qualification' => 'PhD Computer Science, University of Southampton, The United Kingdom, วศ.ม วิศวกรรมไฟฟ้า สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง, วศ.บ วิศวกรรมไฟฟ้าคอมพิวเตอร์ มหาวิทยาลัยเทคโนโลยีมหานคร',
            'branch' => 'PhD Computer Science, วศ.ม วิศวกรรมไฟฟ้า, วศ.บ วิศวกรรมไฟฟ้าคอมพิวเตอร์',
            'user_type' => 'Branch head',
            'email' => 'tsakchan@hotmail.com',
            'email_verified_at' => now(),
            'tel' => null,
            'id_line' => null,
            'teacher_image' => 'teacher_image/TeEVioLD3lfrZVB8NiPa08o4YrBP01MHwHhJU1Vj.jpg',
            'signature_image' => 'https://via.placeholder.com/50',
            'username' => 'sakchan',
            'password' => Hash::make('password'),
            'account_status' => true,
            'created_by' => null,
            'updated_by' => null,
            'remember_token' => Str::random(10),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('teachers')->insert([
            'prefix' => 'อาจารย์สิบเอก',
            'name' => 'ทองล้วน',
            'surname' => 'สิงห์นันท์',
            'academic_position' => 'อาจารย์',
            'educational_qualification' => 'ค.อ.ม เทคโนโลยีคอมพิวเตอร์ สถาบันเทคโนโลยีพระจอมเกล้าพระนครเหนือ, ค.อ.บ วิศวกรรมคอมพิวเตอร์ สถาบันเทคโนโลยีราชมงคลล้านนา วิทยาเขตภาคพายัพ',
            'branch' => 'ค.อ.ม เทคโนโลยีคอมพิวเตอร์, ค.อ.บ วิศวกรรมคอมพิวเตอร์',
            'user_type' => 'Teacher',
            'email' => 'Singnant6@gmail.com',
            'email_verified_at' => now(),
            'tel' => null,
            'id_line' => null,
            'teacher_image' => 'teacher_image/5KdbztGxxEMa1PWG4MzDiXc0aTT52RNBduTkGLQw.jpg',
            'signature_image' => 'https://via.placeholder.com/50',
            'username' => 'tongluan',
            'password' => Hash::make('password'),
            'account_status' => true,
            'created_by' => null,
            'updated_by' => null,
            'remember_token' => Str::random(10),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('teachers')->insert([
            'prefix' => 'อาจารย์ ดร.',
            'name' => 'วิภาสิทธ์',
            'surname' => 'หิรัญรัตน์',
            'academic_position' => 'อาจารย์',
            'educational_qualification' => 'วส.ด. เทคโนโลยีสารสนเทศ มหาวิทยาลัยเทคโนโลยีสุรนารี, ค.อ.ม เทคโนโลยีคอมพิวเตอร์ มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ, วท.บ. วิทยาการคอมพิวเตอร์ มหาวิทยาลัยมหาสารคาม',
            'branch' => 'วส.ด. เทคโนโลยีสารสนเทศ, ค.อ.ม เทคโนโลยีคอมพิวเตอร์, วท.บ. วิทยาการคอมพิวเตอร์',
            'user_type' => 'Teacher',
            'email' => 'Wiphasith@hotmail.com',
            'email_verified_at' => now(),
            'tel' => null,
            'id_line' => null,
            'teacher_image' => 'teacher_image/zHL0UDooglv28Omx3e9i3yQXIhOSl0TSCMXxPGEo.jpg',
            'signature_image' => 'https://via.placeholder.com/50',
            'username' => 'wiphasith',
            'password' => Hash::make('password'),
            'account_status' => true,
            'created_by' => null,
            'updated_by' => null,
            'remember_token' => Str::random(10),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('teachers')->insert([
            'prefix' => 'ผู้ช่วยศาสตราจารย์ ดร.',
            'name' => 'ทองมี',
            'surname' => 'ละครพล',
            'academic_position' => 'ผู้ช่วยศาสตราจารย์',
            'educational_qualification' => 'ปร.ด เทคโนโลยีและการสื่อสารการศึกษา มหาวิทยาลัยมหาสารคาม, กศ.ม เทคโนโลยีและการสื่อสารการศึกษา มหาวิทยาลัยมหาสารคาม, วท.บ สถิติประยุกต์ มหาวิทยาลัยราชภัฎมหาสารคาม',
            'branch' => 'ปร.ด เทคโนโลยีและการสื่อสารการศึกษา, กศ.ม เทคโนโลยีและการสื่อสารการศึกษา, วท.บ สถิติประยุกต์',
            'user_type' => 'Teacher',
            'email' => 'tomranbo@hotmail.com',
            'email_verified_at' => now(),
            'tel' => null,
            'id_line' => null,
            'teacher_image' => 'teacher_image/fnBY33jl9LtoHb3f39bf9yN2ZQHptXSmDvb4tgf4.jpg',
            'signature_image' => 'https://via.placeholder.com/50',
            'username' => 'tongme',
            'password' => Hash::make('password'),
            'account_status' => true,
            'created_by' => null,
            'updated_by' => null,
            'remember_token' => Str::random(10),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('teachers')->insert([
            'prefix' => 'อาจารย์ ดร.',
            'name' => 'อัญวีณ์',
            'surname' => 'ไชยวชิระกัมพล',
            'academic_position' => 'อาจารย์',
            'educational_qualification' => 'ปร.ด วิศวกรรมไฟฟ้าและคอมพิวเตอร์ มหาวิทยาลัยมหาสารคาม, วท.ม วิทยาการคอมพิวเตอร์ มหาวิทยาลัยขอนแก่น, วท.บ วิทยาการคอมพิวเตอร์ มหาวิทยาลัยเทคโนโลยีราชมงคลตะวันออก วิทยาเขตบางพระ',
            'branch' => 'ปร.ด วิศวกรรมไฟฟ้าและคอมพิวเตอร์, วท.ม วิทยาการคอมพิวเตอร์, วท.บ วิทยาการคอมพิวเตอร์',
            'user_type' => 'Teacher',
            'email' => 'anyawee_chai@hotmail.com',
            'email_verified_at' => now(),
            'tel' => null,
            'id_line' => null,
            'teacher_image' => 'teacher_image/rn4In0g21JPwjgBIUdbGv2yfscY5Mi1cdMTWFHHK.jpg',
            'signature_image' => 'https://via.placeholder.com/50',
            'username' => 'anyawee',
            'password' => Hash::make('password'),
            'account_status' => true,
            'created_by' => null,
            'updated_by' => null,
            'remember_token' => Str::random(10),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('teachers')->insert([
            'prefix' => 'อาจารย์',
            'name' => 'วาทการ',
            'surname' => 'มูลไชยสุข',
            'academic_position' => 'อาจารย์',
            'educational_qualification' => 'กำลังศึกษา PhD( Asian Institute of Technology), วศ.ม การวัดคุม สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง, วศ.บ วิศวกรรมไฟฟ้า วิศวกรรมไฟฟ้า มหาวิทยาลัยภาคตะวันออกเฉียงเหนือ',
            'branch' => 'วศ.ม การวัดคุม, วศ.บ วิศวกรรมไฟฟ้า',
            'user_type' => 'Teacher',
            'email' => null,
            'email_verified_at' => now(),
            'tel' => null,
            'id_line' => null,
            'teacher_image' => 'teacher_image/uWPX5bhDblQOgjXaZL2jZC2AIVqN7gpVSrVwQD3K.jpg',
            'signature_image' => 'https://via.placeholder.com/50',
            'username' => 'wathakan',
            'password' => Hash::make('password'),
            'account_status' => true,
            'created_by' => null,
            'updated_by' => null,
            'remember_token' => Str::random(10),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('teachers')->insert([
            'prefix' => 'อาจารย์ ดร.',
            'name' => 'อธิปัตย์',
            'surname' => 'ฤทธิรณ',
            'academic_position' => 'อาจารย์',
            'educational_qualification' => 'ค.อ.ม. เทคโนโลยีคอมพิวเตอร์ สถาบันเทคโนโลยีพระจอมเกล้าพระนครเหนือ, ค.บ. คอมพิวเตอร์ศึกษา สถาบันราชภัชบุรีรัมย์',
            'branch' => 'ค.อ.ม. เทคโนโลยีคอมพิวเตอร์, ค.บ. คอมพิวเตอร์ศึกษา',
            'user_type' => 'Teacher',
            'email' => 'atp_rmuti@hotmail.com',
            'email_verified_at' => now(),
            'tel' => null,
            'id_line' => null,
            'teacher_image' => 'teacher_image/FEQw30fs5z5lEC9PGYuX5z2e0fFK5nkRpNZh9qlT.jpg',
            'signature_image' => 'https://via.placeholder.com/50',
            'username' => 'atipat',
            'password' => Hash::make('password'),
            'account_status' => true,
            'created_by' => null,
            'updated_by' => null,
            'remember_token' => Str::random(10),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('teachers')->insert([
            'prefix' => 'อาจารย์',
            'name' => 'จีรนันท์',
            'surname' => 'ตะสันเทียะ',
            'academic_position' => 'อาจารย์',
            'educational_qualification' => 'ค.อ.ม เทคโนโลยีคอมพิวเตอร์ มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ, วท.บ วิทยาการคอมพิวเตอร์ มหาวิทยาลัยเทคโนโลยีราชมงคลธัญบุรี',
            'branch' => 'ค.อ.ม เทคโนโลยีคอมพิวเตอร์, วท.บ วิทยาการคอมพิวเตอร์',
            'user_type' => 'Admin',
            'email' => 'jeeranunt.ta@gmail.com',
            'email_verified_at' => now(),
            'tel' => null,
            'id_line' => null,
            'teacher_image' => 'teacher_image/AtPTT5dktyIW6rGuSaluLpLhLAAakU0UPJP71heZ.jpg',
            'signature_image' => 'https://via.placeholder.com/50',
            'username' => 'jeeranun',
            'password' => Hash::make('password'),
            'account_status' => true,
            'created_by' => null,
            'updated_by' => null,
            'remember_token' => Str::random(10),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('teachers')->insert([
            'prefix' => 'อาจารย์',
            'name' => 'บุญเหลือ',
            'surname' => 'นาบำรุง',
            'academic_position' => 'อาจารย์',
            'educational_qualification' => 'วศ.ม วิศวกรรมไฟฟ้า-คอมพิวเตอร์ มหาวิทยาลัยเทคโนโลยีมหานคร, ค.อ.บ วิศวกรรมคอมพิวเตอร์ มหาวิทยาลัยเทคโนโลยีราชมงคลอีสาน วิทยาเขตสุรินทร์',
            'branch' => 'วศ.ม วิศวกรรมไฟฟ้า-คอมพิวเตอร์, ค.อ.บ วิศวกรรมคอมพิวเตอร์',
            'user_type' => 'Teacher',
            'email' => 'boonlueo_elec1@hotmail.com',
            'email_verified_at' => now(),
            'tel' => null,
            'id_line' => null,
            'teacher_image' => 'teacher_image/HPS8UcivK5EzQWcb6LEN0jnzZ1qo6q8gR5d6CsY1.jpg',
            'signature_image' => 'https://via.placeholder.com/50',
            'username' => 'boonlueo',
            'password' => Hash::make('password'),
            'account_status' => true,
            'created_by' => null,
            'updated_by' => null,
            'remember_token' => Str::random(10),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('teachers')->insert([
            'prefix' => 'อาจารย์',
            'name' => 'นิพนธ์',
            'surname' => 'พิมพ์เบ้าธรรม',
            'academic_position' => 'อาจารย์',
            'educational_qualification' => 'ค.อ.ม เทคโนโลยีคอมพิวเตอร์ มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ, ค.อ.บ วิศวกรรมคอมพิวเตอร์ มหาวิทยาลัยเทคโนโลยีราชมงคลอีสาน วิทยาเขตสุรินทร์',
            'branch' => 'ค.อ.ม เทคโนโลยีคอมพิวเตอร์, ค.อ.บ วิศวกรรมคอมพิวเตอร์',
            'user_type' => 'Teacher',
            'email' => 'Nipon.pi@rmuti.ac.th',
            'email_verified_at' => now(),
            'tel' => null,
            'id_line' => null,
            'teacher_image' => 'teacher_image/905xtfzQGSnLbaCmFZdfhkJm3Uga8fXeE73wFZBV.jpg',
            'signature_image' => 'https://via.placeholder.com/50',
            'username' => 'nipon',
            'password' => Hash::make('password'),
            'account_status' => true,
            'created_by' => null,
            'updated_by' => null,
            'remember_token' => Str::random(10),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('teachers')->insert([
            'prefix' => 'ผู้ช่วยศาสตราจารย์',
            'name' => 'นราศักดิ์',
            'surname' => 'วงษ์วาสน์',
            'academic_position' => 'ผู้ช่วยศาสตราจารย์',
            'educational_qualification' => 'วศ.ม วิศวกรรมไฟฟ้า (ระบบสมองกลฝังตัว) มหาวิทยาลัยเทคโนโลยีมหานคร, วศ.บ วิศวกรรมไฟฟ้า (วิศวกรรมอิเล็กทรอนิกส์ ) มหาวิทยาลัยเทคโนโลยีมหานคร',
            'branch' => 'วศ.ม วิศวกรรมไฟฟ้า (ระบบสมองกลฝังตัว), วศ.บ วิศวกรรมไฟฟ้า (วิศวกรรมอิเล็กทรอนิกส์ )',
            'user_type' => 'Teacher',
            'email' => 'narasuk2525@gmail.com',
            'email_verified_at' => now(),
            'tel' => null,
            'id_line' => null,
            'teacher_image' => 'teacher_image/bn8NCMZjF1H3HHnqRKqOfSGLoyxEBcspuija4Y0F.jpg',
            'signature_image' => 'https://via.placeholder.com/50',
            'username' => 'narasuk',
            'password' => Hash::make('password'),
            'account_status' => true,
            'created_by' => null,
            'updated_by' => null,
            'remember_token' => Str::random(10),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('teachers')->insert([
            'prefix' => 'ผู้ช่วยศาสตราจารย์',
            'name' => 'อัตพล',
            'surname' => 'คุณเลิศ',
            'academic_position' => 'ผู้ช่วยศาสตราจารย์',
            'educational_qualification' => 'วท.ม เทคโนโลยีสารสนเทศ มหาวิทยาลัยขอนแก่น, วท.บ เทคโนโลยีสารสนเทศ มหาวิทยาลัยอุบลราชธานี',
            'branch' => 'วท.ม เทคโนโลยีสารสนเทศ, วท.บ เทคโนโลยีสารสนเทศ',
            'user_type' => 'Teacher',
            'email' => 'Attapol.ku@rmuti.ac.th',
            'email_verified_at' => now(),
            'tel' => null,
            'id_line' => null,
            'teacher_image' => 'teacher_image/gVr3PgZMuQYxQdAucLAQdy1yKw5quBLHYNnKNEMY.jpg',
            'signature_image' => 'https://via.placeholder.com/50',
            'username' => 'attapol',
            'password' => Hash::make('password'),
            'account_status' => true,
            'created_by' => null,
            'updated_by' => null,
            'remember_token' => Str::random(10),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('teachers')->insert([
            'prefix' => 'อาจารย์ ดร.',
            'name' => 'อนัตต์ชัย',
            'surname' => 'ชุติภาสเจริญ',
            'academic_position' => 'ผู้ช่วยศาสตราจารย์',
            'educational_qualification' => 'ปร.ด. (คอมพิวเตอร์ศึกษา) มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ, ค.อ.ม. (เทคโนโลยีคอมพิวเตอร์) มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ, ค.อ.บ. (เทคโนโลยีคอมพิวเตอร์) มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ',
            'branch' => 'ปร.ด. (คอมพิวเตอร์ศึกษา), ค.อ.ม. (เทคโนโลยีคอมพิวเตอร์), ค.อ.บ. (เทคโนโลยีคอมพิวเตอร์)',
            'user_type' => 'Teacher',
            'email' => 'anuschai.ch@rmuti.ac.th',
            'email_verified_at' => now(),
            'tel' => null,
            'id_line' => null,
            'teacher_image' => 'teacher_image/aDxZkzpSjbrTLo7mSHyCclk3yy422PtD3lJ1FCTp.jpg',
            'signature_image' => 'https://via.placeholder.com/50',
            'username' => 'anutchai',
            'password' => Hash::make('password'),
            'account_status' => true,
            'created_by' => null,
            'updated_by' => null,
            'remember_token' => Str::random(10),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }
}